# This rule is not used by the project oci-compute-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over compute.nvcne-demo.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: oci-compute-operator
    app.kubernetes.io/managed-by: kustomize
  name: ocisecuritypolicy-admin-role
rules:
- apiGroups:
  - compute.nvcne-demo.io
  resources:
  - ocisecuritypolicies
  verbs:
  - '*'
- apiGroups:
  - compute.nvcne-demo.io
  resources:
  - ocisecuritypolicies/status
  verbs:
  - get
