---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - compute.nvcne-demo.io
  resources:
  - ociinstances
  - ocisecuritypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.nvcne-demo.io
  resources:
  - ociinstances/finalizers
  - ocisecuritypolicies/finalizers
  verbs:
  - update
- apiGroups:
  - compute.nvcne-demo.io
  resources:
  - ociinstances/status
  - ocisecuritypolicies/status
  verbs:
  - get
  - patch
  - update
